@startuml 


"Raw ePI"-> "p(ePI)": Annotation


"p(ePI)"->"f(ePI)": Lensing


"f(ePI)"->"e(ePI)": Focusing

note left of "p(ePI)": Annotation of content \nw/ standard terminologies\nAutomatic (NLP)\nSemi-automatic\nManual (ePI editor tool)


note left of "f(ePI)": **Engine**\n JavaScript \nCQL\nOther

@enduml
