@startuml 


"p(ePI)"-> "x(ePI)": adding lenses


"x(ePI)"->"x'(ePI)": data consumed and attached focusing elements


"x'(ePI)"->"f(ePI)": Lenses executed



note right of "x(ePI)": Know and standard Terms\nKnow and standard Profile + IPS\nProduce Standard operations\nLanguage independent



note left of "x'(ePI)": User Profile\nIPS\nOr combination


@enduml
