Instance: bundle-ibrance75-100-125
InstanceOf: BundleUvEpi
Usage: #example
* meta.versionId = "1"
* meta.lastUpdated = "2022-09-08T00:00:00Z"
* identifier.system = "https://www.fda.gov/"
* identifier.value = "ibrance"
* type = #document
* timestamp = "2022-09-08T00:00:00Z"
* entry[0].fullUrl = "Composition/compositionusen"
* entry[=].resource = compositionusen
* entry[+].fullUrl = "Organization/UORG1"
* entry[=].resource = ORG1
* entry[+].fullUrl = "Organization/UORG2"
* entry[=].resource = ORG2
* entry[+].fullUrl = "Organization/UORG3"
* entry[=].resource = ORG3
* entry[+].fullUrl = "Organization/UORG4"
* entry[=].resource = ORG4
* entry[+].fullUrl = "Organization/UORG5"
* entry[=].resource = ORG5
* entry[+].fullUrl = "Ingredient/UUID-CROSPOVIDONE"
* entry[=].resource = UUID-CROSPOVIDONE
* entry[+].fullUrl = "Ingredient/UUID-FDCBLUE2"
* entry[=].resource = UUID-FDCBLUE2
* entry[+].fullUrl = "Ingredient/UUID-FERRIC-OXIDE-RED"
* entry[=].resource = UUID-FERRIC-OXIDE-RED
* entry[+].fullUrl = "Ingredient/UUID-FERRIC-OXIDE-YELLOW"
* entry[=].resource = UUID-FERRIC-OXIDE-YELLOW
* entry[+].fullUrl = "Ingredient/UUID-HYPROMELLOSE"
* entry[=].resource = UUID-HYPROMELLOSE
* entry[+].fullUrl = "Ingredient/UUID-MAGNESIUM-STEARATE"
* entry[=].resource = UUID-MAGNESIUM-STEARATE
* entry[+].fullUrl = "Ingredient/UUID-MICROCRYSTALLINE-CELLULOSE"
* entry[=].resource = UUID-MICROCRYSTALLINE-CELLULOSE
* entry[+].fullUrl = "Ingredient/palbociclib75"
* entry[=].resource = palbociclib75
* entry[+].fullUrl = "Ingredient/UUID-PALBOCICLIB100"
* entry[=].resource = UUID-PALBOCICLIB100
* entry[+].fullUrl = "Ingredient/UUID-PALBOCICLIB125"
* entry[=].resource = UUID-PALBOCICLIB125
* entry[+].fullUrl = "Ingredient/UUID-SILICON-DIOXIDE"
* entry[=].resource = UUID-SILICON-DIOXIDE
* entry[+].fullUrl = "Ingredient/UUID-SUCCINIC-ACID"
* entry[=].resource = UUID-SUCCINIC-ACID
* entry[+].fullUrl = "Ingredient/UUID-TITANIUM-DIOXIDE"
* entry[=].resource = UUID-TITANIUM-DIOXIDE
* entry[+].fullUrl = "Ingredient/UUID-TRIACETIN"
* entry[=].resource = UUID-TRIACETIN
* entry[+].fullUrl = "ManufacturedItemDefinition/UUID-MID-PALBOCICLIB75"
* entry[=].resource = UUID-MID-PALBOCICLIB75
* entry[+].fullUrl = "ManufacturedItemDefinition/UUID-MID-PALBOCICLIB75"
* entry[=].resource = UUID-MID-PALBOCICLIB100
* entry[+].fullUrl = "ManufacturedItemDefinition/UUID-MID-PALBOCICLIB125"
* entry[=].resource = UUID-MID-PALBOCICLIB125
* entry[+].fullUrl = "MedicinalProductDefinition/UUID-MPD-PALBOCICLIB75"
* entry[=].resource = UUID-MPD-PALBOCICLIB75
* entry[+].fullUrl = "MedicinalProductDefinition/UUID-MPD-PALBOCICLIB100"
* entry[=].resource = UUID-MPD-PALBOCICLIB100
* entry[+].fullUrl = "MedicinalProductDefinition/UUID-MPD-PALBOCICLIB125"
* entry[=].resource = UUID-MPD-PALBOCICLIB125
* entry[+].fullUrl = "AdministrableProductDefinition/UUID-APD-PALBOCICLIB75"
* entry[=].resource = UUID-APD-PALBOCICLIB75
* entry[+].fullUrl = "AdministrableProductDefinition/UUID-APD-PALBOCICLIB100"
* entry[=].resource = UUID-APD-PALBOCICLIB100
* entry[+].fullUrl = "AdministrableProductDefinition/UUID-APD-PALBOCICLIB125"
* entry[=].resource = UUID-APD-PALBOCICLIB125
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB75-TAB-MONTH"
* entry[=].resource = UUID-PPD-PALBOCICLIB75-TAB-MONTH
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB75-TAB-WEEK"
* entry[=].resource = UUID-PPD-PALBOCICLIB75-TAB-WEEK
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB100-TAB-MONTH"
* entry[=].resource = UUID-PPD-PALBOCICLIB100-TAB-MONTH
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB100-TAB-WEEK"
* entry[=].resource = UUID-PPD-PALBOCICLIB100-TAB-WEEK
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB125-TAB-MONTH"
* entry[=].resource = UUID-PPD-PALBOCICLIB125-TAB-MONTH
* entry[+].fullUrl = "PackagedProductDefinition/UUID-PPD-PALBOCICLIB125-TAB-WEEK"
* entry[=].resource = UUID-PPD-PALBOCICLIB125-TAB-WEEK
* entry[+].fullUrl = "RegulatedAuthorization/UUID-RA-PALBOCICLIB75"
* entry[=].resource = UUID-RA-PALBOCICLIB75
* entry[+].fullUrl = "RegulatedAuthorization/UUID-RA-PALBOCICLIB100-TAB-WEEK"
* entry[=].resource = UUID-RA-PALBOCICLIB100-TAB-WEEK
* entry[+].fullUrl = "RegulatedAuthorization/UUID-RA-PALBOCICLIB125-TAB-MONTH"
* entry[=].resource = UUID-RA-PALBOCICLIB125-TAB-MONTH
* entry[+].fullUrl = "RegulatedAuthorization/UUID-RA-PALBOCICLIB125"
* entry[=].resource = UUID-RA-PALBOCICLIB125
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-carbamazepine"
* entry[=].resource = interaction-carbamazepine-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-enzalutamide"
* entry[=].resource = interaction-enzalutamide-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-stjohnswort"
* entry[=].resource = interaction-stjohnswort-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-alfentanil"
* entry[=].resource = interaction-alfentanil-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-cyclosporine"
* entry[=].resource = interaction-cyclosporine-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-dihydroergotamine"
* entry[=].resource = interaction-dihydroergotamine-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-ergotamine"
* entry[=].resource = interaction-ergotamine-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-everolimus"
* entry[=].resource = interaction-everolimus-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-fentanyl"
* entry[=].resource = interaction-fentanyl-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-pimozide"
* entry[=].resource = interaction-pimozide-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-quinidine"
* entry[=].resource = interaction-quinidine-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-sirolimus"
* entry[=].resource = interaction-sirolimus-id
* entry[+].fullUrl = "ClinicalUseDefinition/interaction-tacrolimus"
* entry[=].resource = interaction-tacrolimus-id
* entry[+].fullUrl = "ClinicalUseDefinition/indication-hrposher2"
* entry[=].resource = indication-hrposher2