
### List all available preprocessors

GET https://fosps.gravitatehealth.eu/focusing/preprocessing

### List All available lenses

GET https://fosps.gravitatehealth.eu/focusing/lenses



### testing focusing lens pregancy MVP2 with DIV - doesnt work

POST http://fosps.gravitatehealth.eu/focusing/focus/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1


### testing focusing lens pregancy DIV with DIV - should work

POST http://fosps.gravitatehealth.eu/focusing/focus/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165?preprocessors=preprocessing-service-manual&lenses=lens-selector-div_pregnancy&patientIdentifier=alicia-1

### testing focusing lens pregancy DIV (epi preprocessed) with DIV - works


POST http://fosps.gravitatehealth.eu/focusing/focus/processedbundledovato-en?preprocessors=preprocessing-service-manual&lenses=lens-selector-div_pregnancy&patientIdentifier=alicia-1


### testing focusing lens HIV DIV (multiple pedros)

POST http://fosps.gravitatehealth.eu/focusing/focus/processedbundledovato-en?preprocessors=preprocessing-service-manual&lenses=lens-selector-div_HIV&patientIdentifier=Pedro-1


### check epi for using in diabetes

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165
### testing focusing lens diabetes DIV (cecilia)

POST http://fosps.gravitatehealth.eu/focusing/focus/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165?preprocessors=preprocessing-service-manual&lenses=lens-selector-div_diabetes&patientIdentifier=Cecilia-1

