
@host = https://fosps.gravitatehealth.eu

@host = https://gravitate-health.lst.tfo.upm.es

###

GET {{host}}/epi/api/fhir/Composition?_language=es&category=R&subject.identifier=EU/1/18/1326/001
### List all available preprocessors

###

GET {{host}}/epi/api/fhir/Composition

GET  {{host}}/epi/api/fhir/Bundle?composition=https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition/composition-en-b6ced64d25ea2c8da6c6099386f14db1

###
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition?_language=no


####
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition/FK545806-COMP