### get patients
GET https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Patient/


### get patients
GET https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Patient/alicia-patient



### get patients
DELETE https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Patient/506
