### test with MP

GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/List?_elements=id&_count=100&_sort=_lastUpdated

#### deletes
DELETE https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/List/listBiktarvyproc

### delete 1
DELETE https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/List/list-dovato
 #       "id": "list-karvea",
 #       "id": "list-bundlepackageleaflet-enbrelsolution",
 #       "id": "list-humalog",
 #       "id": "list-flucelvax",
 #       "id": "list-biktarvy",
 #       "id": "list-xenical",
 #       "id": "list-dovato",
