### process of alicia ES
@host = https://gravitate-health.lst.tfo.upm.es
# RAW ePI for biktarvy in spanish

GET  {{host}}/epi/api/fhir/Bundle?composition.subject.identifier=EU/1/18/1326/001&composition._language=es


#### 
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Bundle?identifier=EU%2F1%2F18%2F1289%2F001&_language=es&composition.category=R




