### List All available lenses

GET https://fosps.gravitatehealth.eu/focusing/lenses


### List All available lenses DEV

GET https://gravitate-health.lst.tfo.upm.es/focusing/lenses

### Test all the lenses, individually.

### Test Lens: Pregnancy
POST https://fosps.gravitatehealth.eu/focusing/focus/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1


### condition lens
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_conditions&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html

< ./examples/preprocessed-biktarvy.json


### intollerance lens
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_allergyintollerance&patientIdentifier=helen-1
content-type: application/json
Accept: application/json
#Accept: text/html

< ./examples/lactose-preproc-karvea.json



### interaction lens
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_interaction&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html

< ./examples/preprocessed-biktarvy.json

### interaction lens app
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-es-04c9bd6fb89d38b2d83eced2460c4dc1?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_interaction&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html


### interaction lens app bik
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_interaction&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html




### summary Lens
GET http://gravitate-health.lst.tfo.upm.es/ai/summary/bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&patientIdentifier=alicia-1&lenses=lens-summary-2&model=graviting-llama

### summary Lens
GET http://gravitate-health.lst.tfo.upm.es/ai/summary/bundlepackageleaflet-es-29436a85dac3ea374adb3fa64cfd2578?preprocessors=preprocessing-service-manual&patientIdentifier=alicia-1&lenses=lens-summary-2&model=graviting-llama


### summary Lens
GET http://gravitate-health.lst.tfo.upm.es/ai/summary/bundlepackageleaflet-es-29436a85dac3ea374adb3fa64cfd2578?preprocessors=preprocessing-service-manual&patientIdentifier=Pedro-1&lenses=lens-summary-2&model=graviting-llama

### summary Lens biktarvy
GET http://gravitate-health.lst.tfo.upm.es/ai/summary/bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&patientIdentifier=alicia-1&lenses=lens-summary-2&model=graviting-llama


#### 

#bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9 bik
#bundlepackageleaflet-es-4fab126d28f65a1084e7b50a23200363 xenical
#    "lens-selector-mvp2_diabetes",
   # "lens-selector-mvp2_interaction",
   # "lens-selector-mvp2_pregnancy",
### interaction lens app bik
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-es-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_interaction&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html

### interaction lens app bik
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-es-4fab126d28f65a1084e7b50a23200363?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json
#Accept: text/html



### Test Lens: Pregnancy himss
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundle-met-proc?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1
content-type: application/json
Accept: application/json


### Test Lens: Pregnancy himss


## new lenses
GET http://gravitate-health.lst.tfo.upm.es/focusing/lenses


### a lens
GET http://gravitate-health.lst.tfo.upm.es/focusing/lenses/pregnancy-lens


### a lens

GET https://gravitate-health.lst.tfo.upm.es/ips/api/fhir/Library/588


### troubleshoot app

GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition?subject.identifier=EU/1/20/1457/002&_language=en


###EU/1/20/1457/002
### first query

GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/MedicinalProductDefinition?name%3Acontains=xen


### troubleshoot app

GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition?subject=mp962167f0883d517c612253bd6d108856


### toubleshoott llens pregnancy dovato pedro

### Test Lens: Pregnancy
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/processedbundledovato-en-49178f16170ee8a6bc2a4361c1748d5f?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=Pedro-1


### that worked
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-49178f16170ee8a6bc2a4361c1748d5f?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy-collapse&patientIdentifier=Pedro-1

#### RMM
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-manual&lenses=rmm-lens&patientIdentifier=alicia-1
Accept: application/json


### lens with two preproces


### with preproc
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-mvp2&preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=Pedro-1
Accept: application/json

### without preproc

POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-1a7318638ddbbeb084ef416e717b6fdb?preprocessors=preprocessing-service-mvp2&preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=Pedro-1
Accept: application/json
