### List all available preprocessors

GET https://gravitate-health.lst.tfo.upm.es/focusing/preprocessing

### current preprocessor - dumb


POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleafletxyntha?preprocessors=preprocessing-service-mvp2&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1

### current preprocessor - dumb 2

POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-94a96e39cfdcd8b378d12dd4063065f9?preprocessors=preprocessing-service-mvp2&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=alicia-1
Accept: application/json
