
@host = https://fosps.gravitatehealth.eu

@host = https://gravitate-health.lst.tfo.upm.es

###

GET {{host}}/epi/api/fhir/Composition?_language=es&category=R&subject.identifier=EU/1/18/1326/001
### List all available preprocessors

###

GET {{host}}/epi/api/fhir/Composition

GET  {{host}}/epi/api/fhir/Bundle?composition=https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition/composition-en-b6ced64d25ea2c8da6c6099386f14db1

###
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition?_language=no

###
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition?_language=pt

####
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Composition/FK545806-COMP


### get data
GET https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?_language=es&category=R&subject.identifier=EU/1/18/1326/001



### testing focusing lens pregancy MVP2 with DIV - doesnt work

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle?type=document

### get the bundle

GET  https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle/bundlepackageleaflet-2d49ae46735143c1323423b7aea24165


### get bundle of raw epi

GET  https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle?composition.identifier=dd

### get bundle of raw epi

GET  https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle?composition.subject=MedicinalProductDefinition/mp2412867d9a0e15f82f11047ad93bdbad


### testing focusing lens pregancy MVP2 with DIV - doesnt work

GET https://fosps.gravitatehealth.eu/ips/api/fhir/Composition?subject.identifier=alicia-1


### testing focusing lens pregancy MVP2 with DIV - doesnt work

GET https://fosps.gravitatehealth.eu/ips/api/fhir/Patient/$summary?identifier=alicia-1




### testing all Ids

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?&category=http://hl7.eu/fhir/ig/gravitate-health/CodeSystem/epicategory-cs|R&_elements=identifier,title



### testing language

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?subject=MedicinalProductDefinition/mp2412867d9a0e15f82f11047ad93bdbad&category=http://hl7.eu/fhir/ig/gravitate-health/CodeSystem/epicategory-cs|P&_language=en

### testing language

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?_language=en


#### testing 

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Composition/Processedcompositionf4d45353edcb21af3718d3a0df94a4d8/$document\



#### testing 

GET https://fosps.gravitatehealth.eu/epi/api/fhir/Bundle/Processedcompositionf4d45353edcb21af3718d3a0df94a4d8/$document



### mark-all
POST https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/$mark-all-resources-for-reindexing



### reindex
POST https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/$reindex




### get bundles
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Bundle


### get bundles
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/Bundle/bundlepackageleaflet-es-proc-2f37d696067eeb6daf1111cfc3272672




### POST SEARCH PARAMETER

POST https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/SearchParameter
content-type: application/json
Accept: application/json

{
  "resourceType": "SearchParameter",
  "id": "Composition-category",
  "url": "http://gravitate-health.com/SearchParameter/composition-category",
  "name": "composition-category",
  "title": "composition-category",
  "status": "active",
  "experimental": false,
  "publisher": "gravitate-health",
  "description": "Search on composition category",
  "code": "composition.category",
  "base": [ "Bundle" ],
  "type": "token",
  "expression": "Bundle.entry[0].resource.as(Composition).category"
}

### searching
GET https://fosps.gravitatehealth.eu/epi/api/fhir/MedicinalProductDefinition?name:contains=bl

###epi for 

GET  https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?subject=mpb62cc095c7be2116a8a65157286376a3&category=R&_language=en


#### epi identifier

GET  https://fosps.gravitatehealth.eu/epi/api/fhir/Composition?subject.identifier=hack-1&category=R&_language=en


### get bundles
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/DocumentReference?subject.identifier=EU/1/18/1326/001


### get bundles
GET https://gravitate-health.lst.tfo.upm.es/epi/api/fhir/List?subject.identifier=EU/1/18/1326/001
